### ISSUE TITLE
Set includePath relative

### ISSUE THREAD

**Issue by skyrpex** [josa42/atom-linter-less#18]
I think it makes more sense to set include paths relative to the project.

For example, I want my less linter to be able to find inside my node_modules directory.

What do you think?

**Comment by josa42** [comment]
The problem with this that these settings need to be per project. And I haven't found a good solution for that.

The only thing I found was the [project-manager](https://atom.io/packages/project-manager) package. But I don't like to depend on other packages.

Or how would you do it?

**Comment by skyrpex** [comment]
What about using a .lessrc or something similar? The options for the less
compiler would be there, and we could use helpers.findFile to look for the
file.

**Comment by josa42** [comment]
`.lessrc` maybe an option. Further discussion here: #21
