### ISSUE TITLE
.lessrc linter configuration file

### ISSUE THREAD

**Issue by Regaddi** [josa42/atom-linter-less#21]
Hi,

it would be great, if you respected a .lessrc file, which is included in projects.
Since there are many different ways to resolve LESS import dependencies I'd like to configure the linter options for the specific project settings in a configuration file.

http://github.com/assemble/assemble-less for example respects such .lessrc or .lessrc.yml files, but I think this is not a standard way.
(https://github.com/assemble/assemble-less/blob/master/test/.lessrc)

scss-lint provides such configuration, too (well, ok, it's scss :smile:): https://github.com/brigade/scss-lint/blob/master/config/default.yml

You've already implemented the Include Path setting, but this is not really satisfying for me, since I work in different project setups and don't want to enter every single include path for every project I work in :smile:

**Comment by josa42** [comment]
Good point. I'll look into it.

**Comment by josa42** [comment]
The official support a config file doesn't seem to be coming any time soon (less/less.js#1893).

But I think we I could implement support for [assemble/assemble-less](http://github.com/assemble/assemble-less)'s `.lessrc` or `.lessrc.yml` files. I would put it behind a setting. I am not sure yet if it should be on or off by default.
