### ISSUE TITLE
Alphabetic property ordering warning

### ISSUE THREAD

**Issue by JohnD3S** [josa42/atom-linter-less#24]
Is there anyway to disable the check for alphabetized property ordering?

These alerts are distracting for developers who don't order their properties alphabetically

**Comment by josa42** [comment]
@JohnD3S I am pretty sure this is coming from a different linter. Which linters do you have installed?

**Comment by JohnD3S** [comment]
Hello @josa42 you were right as I was using https://atom.io/packages/linter-lesshint alongside your package. Thanks for the quick reply.
