### ISSUE TITLE
Getting undefined variable error when it is defined.

### ISSUE THREAD

**Issue by newelement** [josa42/atom-linter-less#30]
Greetings. I'm getting the error even when the variable is defined. It does exist on a variables.less file, but it is included on the file I'm working on. Am I doing something wrong?

**Comment by newelement** [comment]
I guess I'm doing something wrong. When I check it ignore variables I now get errors on using mixins. Am I settings my include paths wrong? This is in a Wordpress theme folder.
<img width="439" alt="settings_ __users_donjones_sites_maninis" src="https://cloud.githubusercontent.com/assets/188085/13149125/4569e58e-d62e-11e5-9258-a22290ff52e4.png">

**Comment by josa42** [comment]
Can you give me an example on how to to reproduce this?

**Comment by newelement** [comment]
Yeah let me make a quick sample.

**Comment by newelement** [comment]
[Lesslint.zip](https://github.com/josa42/atom-linter-less/files/136811/Lesslint.zip)
If you open src/pages/about.less in my editor I get an error that the @yellow variable is undefined, but it is defined in src/variables/colors.less and is imported on src/style.less

**Comment by josa42** [comment]
Ok. This is pretty much the same issue, which was already discussed in #6.

When you lint `src/pages/about.less` it basically executes `lessc src/pages/about.less`. Therefore the variables defined in `src/variables/colors.less` are not imported / defined.

The option **Ignore Undefined Variables** should solve that issue.

**Comment by josa42** [comment]
But you are right, same thing should be available for mixins.

**Comment by newelement** [comment]
Ah ok, thanks.
