### ISSUE TITLE
Built-in Atom files/variables

### ISSUE THREAD

**Issue by brettz9** [josa42/atom-linter-less#37]
In looking at some Less code (in the file-type-icons package), certain errors are occurring, apparently because they are referencing built-in Atom files or variables which are not available at a location relative to the current file.

Some examples include:

```less
@import "ui-variables";
```

and

```less
line-height: @component-line-height;
```

Could you allow a config file setting which indicates which variables are predefined (or to indicate that this is for an Atom package)?

**Comment by josa42** [comment]
This happens because `less` does not know where to find `ui-variables.less`.

You have 2 options:

1. Add the path to a `.lessrc` file in you project.
2. Set the option "Ignore undefined mixins" to true
